[package]
name = "rqtree"
version = "0.1.0"
authors = ["Kevin <quebin31@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
lab = "0.7.2"
delta_e = "0.2"
imageproc = "0.19"